### ISSUE TITLE
[Vote-Listener/ERROR] [votifier]: Error handling socket connection!

### ISSUE THREAD

**Issue by MyWorldNetwork** [UpcraftLP/Voting#12]
Votifier 1.3.0 running on a 1.12.2 server.

While seemingly very similar to another issue raised but related to all 5 sites i've tried so far, none of which are FTB-related.

[Vote-Listener/ERROR] [votifier]: Error handling socket connection!
javax.crypto.BadPaddingException: Decryption error
	at sun.security.rsa.RSAPadding.unpadV15(Unknown Source) ~[?:1.8.0_191]
	at sun.security.rsa.RSAPadding.unpad(Unknown Source) ~[?:1.8.0_191]
	at com.sun.crypto.provider.RSACipher.doFinal(RSACipher.java:363) ~[sunjce_provider.jar:1.8.0_181]
	at com.sun.crypto.provider.RSACipher.engineDoFinal(RSACipher.java:389) ~[sunjce_provider.jar:1.8.0_181]
	at javax.crypto.Cipher.doFinal(Cipher.java:2164) ~[?:1.8.0_191]
	at com.github.upcraftlp.votifier.util.RSAUtil.decrypt(RSAUtil.java:21) ~[RSAUtil.class:1.3.0]
	at com.github.upcraftlp.votifier.net.NetworkListenerThread.run(NetworkListenerThread.java:52) [NetworkListenerThread.class:1.3.0]

Sites attempted:

http://mc-servers.com
https://minecraft-mp.com
https://minecraftservers.biz
https://www.serverpact.com
http://topg.org/

ALL confirm vote successful all result in identical error thrown up by server console.

I did try the workaround presented but could not find the exact wording displayed and and not java-savvy enough to understand where/ what to change.

**Comment by MyWorldNetwork** [comment]
Add https://topminecraftservers.org to the list...

**Comment by AngelShadow9451** [comment]
Are you hosting the server yourself or with a server hoster?

**Comment by MyWorldNetwork** [comment]
server host, GTXGaming.co.uk

**Comment by AngelShadow9451** [comment]
Make sure you have the additional ports open for Votifier. I was able to use Topg and Minecraft-mp.com, but as I still have this issue: #11 
I can not use the mod.
If you need further help getting the additional ports open I suggest contacting the Server hoster and seeing if you can have them opened.

**Comment by MyWorldNetwork** [comment]
What are the additional ports?
Server hosts have confirmed ALL ports are open which seemed like a red flag but they assure me that their data centre has software which filters out legit queries from generic ones

**Comment by AngelShadow9451** [comment]
The additional port is located in the config file.

**Comment by MyWorldNetwork** [comment]
I didn't remember seeing any additional ports listed in the config so went back and checked. I can confirm there are no additional ports specifically listed.

**Comment by AngelShadow9451** [comment]
It is literally the second thing in the config file. By "additional ports" i was referring to the server side. It is listed as a "listener port" in the config.

**Comment by MyWorldNetwork** [comment]
Checked again. No additional ports listed. I believe you're mistaking the 'port range' for 'additional ports'. That or you have a config which is different from the default supplied with the mod.

**Comment by AngelShadow9451** [comment]
You need to make sure that the ADDITIONAL PORTS ON YOUR SERVER that you have choosen as your listening port are opened as seen here in the screenshots of both my server and config file.
http://imgur.com/iEwZvyX
http://imgur.com/VgzyFRN
i.e. if you still have it set to the default port make sure port 8192 is open. In my case, I had to change the port as that is the one my hoster allowed.

**Comment by MyWorldNetwork** [comment]
So again and now confirmed by your screenshots AND previously addressed.
The config does not specifically mention additional ports, simply your host list an additional ports section and have specific requirements as to which port YOU can use. I have already stated that the hosts have confirmed the ports are open.
With that aside I am no further forward and everything is set up as it should be.

**Comment by TheMaddog91** [comment]
Hi all I am having this exact issue too. I was using SpongeForge on an old 3.0.8 Sevtech server using the port 8192. However I have since completely wiped that server and moved to Sevtech 3.1.2 with no SpongeForge.

I have added my server on various voting sites and all of which spew out errors in my console. I've tried downgrading, however the same error persists.

I have attached my error below:
https://pastebin.com/eLFvDb3Q

Please take a look, any help is seriously grateful thank you for your time.

**Comment by AngelShadow9451** [comment]
Have you asked the hoster to open the extra/additional/required ports as I have stated above as this fixed it for me...

**Comment by TheMaddog91** [comment]
I there I have tried opening additional ports, I've also changed the port and ensured that the port wasn't in use. It's still not working so I'm going to have to leave it

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
